-- Insert test user data for RLS testing
-- Note: Actual auth.users entries must be created via Supabase Auth, not direct SQL
-- This migration creates sample generation data for testing purposes

-- Test data will be inserted after users sign up via the application
-- This file documents the test structure

-- Example test user IDs (will be generated by Supabase Auth):
-- Test User A: Sign up with email test-user-a@example.com
-- Test User B: Sign up with email test-user-b@example.com

-- Example project for Test User A
-- INSERT INTO projects (user_id, title, topic) VALUES
-- ('test-user-a-uuid', 'AI Investment Video', 'The Future of AI in Investing');

-- Example generation for Test User A
-- INSERT INTO generations (user_id, type, title, content, metadata) VALUES
-- ('test-user-a-uuid', 'script', 'AI Investment Script', 
--  '{"title": "The Future of AI in Investing", "scenes": []}',
--  '{"model": "google/gemini-2.5-flash-exp:free", "sceneCount": 6}');

-- Example guest generation (for migration testing)
-- INSERT INTO generations (guest_session_id, type, title, content, metadata) VALUES
-- ('guest-session-uuid', 'script', 'Guest Script', 
--  '{"title": "Test Guest Content", "scenes": []}',
--  '{"model": "google/gemini-2.5-flash-exp:free", "sceneCount": 4}');

-- Test cases to verify:
-- 1. User A can read their own generations
-- 2. User B cannot read User A's generations
-- 3. Guest generations can be migrated to authenticated user
-- 4. Guest generations older than 10 days are cleaned up

COMMENT ON TABLE projects IS 'Stores user video projects';
COMMENT ON TABLE generations IS 'Stores all generated content (scripts, images, videos) for both authenticated users and guests';
COMMENT ON COLUMN generations.guest_session_id IS 'UUID for guest sessions, migrated to user_id upon login';
COMMENT ON COLUMN generations.content IS 'JSONB containing the actual generated content (scripts, image URLs, video URLs)';
COMMENT ON COLUMN generations.metadata IS 'JSONB containing generation parameters (model, provider, scene count, etc)';
